### ISSUE TITLE
Allow autonext timer to be editted by users

### ISSUE THREAD

**Issue by canhnd58** [canhnd58/learn-ielts#6]
- The timer becomes editable on being clicked. May use [react-contenteditable](https://github.com/lovasoa/react-contenteditable) component (already installed) or any other preferred method. **Note** that in the [example](https://github.com/lovasoa/react-contenteditable), they use es5 react syntax `React.createClass` instead of `extends Component`
- When users press Enter or the component loses focus, update the new timer.
- Forget 'bout all the above if there's any better way.

**Comment by lehainam-dev** [comment]
Can I take response for this issue? Tùng are playing Dota League right now :))

**Comment by tungnt-580** [comment]
oke
